"""
train_gait_cnn.py — Fixed Version (No Data Leakage)
=====================================================
Changes from v1:
  - Input: 56 subcarriers (matches ESP32 live inference)
  - Architecture: Deep 2D CNN (Conv2D blocks + GlobalAveragePooling)
  - EarlyStopping monitors val_accuracy with patience=5
  - ModelCheckpoint saves best epoch
  - DATA LEAKAGE FIX: Removed validation_split=0.15 from model.fit().
    Now loads X_val.npy / y_val.npy (generated by preprocess_gait.py at the
    FILE level before windowing). Adjacent windows from the same recording
    can no longer leak across the train/val boundary.
  - Reduced max epochs: 100 → 40
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt
import json
import os

# ── Model Architecture ────────────────────────────────────────────────────────
def build_gait_model(n_timesteps, n_features, n_classes):
    """
    Deep 2D CNN for HAR on CSI amplitude heatmaps.
    Treats the (Time, Subcarriers) matrix as a 1-channel image.
    Includes data augmentation (Noise, Translation) to prevent overfitting.
    """
    # Note: Input shape will be (n_timesteps, n_features, 1)
    inp = tf.keras.Input(shape=(n_timesteps, n_features, 1), name='csi_input')

    # Data Augmentation (active only during training)
    x = layers.GaussianNoise(0.05)(inp)
    # Randomly shift time by up to 10%
    x = layers.RandomTranslation(height_factor=0.1, width_factor=0.0)(x)

    # Block 1 — (32 filters)
    x = layers.Conv2D(32, kernel_size=(5, 3), padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = layers.Dropout(0.2)(x)

    # Block 2 — (64 filters)
    x = layers.Conv2D(64, kernel_size=(3, 3), padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = layers.Dropout(0.25)(x)

    # Block 3 — (128 filters)
    x = layers.Conv2D(128, kernel_size=(3, 3), padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.MaxPooling2D(pool_size=(2, 2))(x)
    x = layers.Dropout(0.3)(x)

    # Block 4 — (256 filters) - Increased capacity
    x = layers.Conv2D(256, kernel_size=(3, 3), padding='same', activation='relu')(x)
    x = layers.BatchNormalization()(x)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.4)(x)

    # Classifier head
    x = layers.Dense(128, activation='relu')(x)
    x = layers.Dropout(0.3)(x)
    out = layers.Dense(n_classes, activation='softmax', name='activity')(x)

    return models.Model(inp, out, name='gait_cnn_2d')



# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    script_dir    = os.path.dirname(os.path.abspath(__file__))
    processed_dir = os.path.join(os.path.dirname(script_dir), 'processed')
    model_dir     = script_dir
    os.makedirs(model_dir, exist_ok=True)

    # ── Load data ──
    print('Loading data...')
    X_train = np.load(os.path.join(processed_dir, 'X_train.npy'))
    y_train = np.load(os.path.join(processed_dir, 'y_train.npy'))
    X_val   = np.load(os.path.join(processed_dir, 'X_val.npy'))
    y_val   = np.load(os.path.join(processed_dir, 'y_val.npy'))
    X_test  = np.load(os.path.join(processed_dir, 'X_test.npy'))
    y_test  = np.load(os.path.join(processed_dir, 'y_test.npy'))

    with open(os.path.join(processed_dir, 'label_map.json')) as f:
        class_to_id = json.load(f)
    labels   = [k for k, _ in sorted(class_to_id.items(), key=lambda kv: kv[1])]
    n_classes = len(labels)

    # Squeeze trailing channel dimension if present (legacy compat)
    if X_train.ndim == 4 and X_train.shape[3] == 1:
        X_train = X_train.squeeze(-1)
        X_val   = X_val.squeeze(-1)
        X_test  = X_test.squeeze(-1)

    n_timesteps = X_train.shape[1]
    n_features  = X_train.shape[2]

    # For 2D CNN, we need a 4D tensor (Batch, Time, Subcarriers, Channels=1)
    X_train = np.expand_dims(X_train, axis=-1)
    X_val   = np.expand_dims(X_val,   axis=-1)
    X_test  = np.expand_dims(X_test,  axis=-1)

    print(f'X_train: {X_train.shape}  X_val: {X_val.shape}  X_test: {X_test.shape}  n_classes: {n_classes}')
    print(f'Train dist: { dict(zip(*np.unique(y_train, return_counts=True))) }')
    print(f'Val   dist: { dict(zip(*np.unique(y_val,   return_counts=True))) }')
    print(f'Test  dist: { dict(zip(*np.unique(y_test,  return_counts=True))) }')
    print(f'Data stats: mean={X_train.mean():.4f}, std={X_train.std():.4f}')

    # ── Model ──
    model = build_gait_model(n_timesteps, n_features, n_classes)
    model.summary()

    # ── Class weights (handle imbalance) ──
    classes = np.unique(y_train)
    weights = compute_class_weight('balanced', classes=classes, y=y_train)
    class_weight_dict = dict(zip(classes.tolist(), weights.tolist()))
    print(f'\nClass weights: {class_weight_dict}')

    # ── Compile (CosineDecay Optimizer) ──
    steps_per_epoch = len(X_train) // 32
    lr_schedule = tf.keras.optimizers.schedules.CosineDecay(
        initial_learning_rate=0.002,
        decay_steps=steps_per_epoch * 100,  # 100 epochs
        alpha=0.01  # Minimum LR = 0.002 * 0.01
    )
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=lr_schedule),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    # ── Callbacks ──
    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor='val_accuracy', patience=5,
            restore_best_weights=True, verbose=1
        ),
        tf.keras.callbacks.ModelCheckpoint(
            os.path.join(model_dir, 'gait_cnn_best.h5'),
            monitor='val_accuracy', save_best_only=True, verbose=1
        ),
    ]

    # ── Train ──
    # DATA LEAKAGE FIX: Use explicit validation_data from the file-level val split
    # instead of validation_split=0.15 (which would randomly pick windowed rows
    # that overlap heavily with training windows).
    print('\nTraining (max 40 epochs with early stopping)...')
    history = model.fit(
        X_train, y_train,
        epochs=40,
        batch_size=32,
        validation_data=(X_val, y_val),
        class_weight=class_weight_dict,
        callbacks=callbacks,
        shuffle=True,
        verbose=1
    )

    # ── Evaluate ──
    print('\nEvaluating on test set...')
    loss, acc = model.evaluate(X_test, y_test, verbose=0)
    print(f'Test Accuracy: {acc:.4f}  |  Loss: {loss:.4f}')

    y_pred = np.argmax(model.predict(X_test, verbose=0), axis=1)

    print('\nClassification Report:')
    print(classification_report(y_test, y_pred, target_names=labels))

    cm = confusion_matrix(y_test, y_pred)
    print('\nConfusion Matrix:')
    header = f"{'':>10} | " + ' | '.join([f'Pred:{lbl[:6]:>6}' for lbl in labels])
    print(header)
    print('-' * len(header))
    for i, tl in enumerate(labels):
        row = f'True:{tl[:6]:<5} | ' + ' | '.join([f'{cm[i,j]:>12}' for j in range(len(labels))])
        print(row)

    # ── Confusion matrix plot ──
    fig, ax = plt.subplots(figsize=(8, 6))
    im = ax.imshow(cm, cmap='Blues')
    fig.colorbar(im)
    ax.set_xticks(range(n_classes)); ax.set_xticklabels(labels, rotation=45, ha='right')
    ax.set_yticks(range(n_classes)); ax.set_yticklabels(labels)
    ax.set_xlabel('Predicted'); ax.set_ylabel('True')
    ax.set_title('Gait CNN-LSTM Confusion Matrix')
    for i in range(n_classes):
        for j in range(n_classes):
            ax.text(j, i, str(cm[i, j]), ha='center', va='center',
                    color='white' if cm[i, j] > cm.max() / 2 else 'black', fontsize=9)
    plt.tight_layout()
    plt.savefig(os.path.join(model_dir, 'gait_confusion_matrix_cnn.png'), dpi=150)
    plt.close()

    # ── Training curves ──
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
    ax1.plot(history.history['accuracy'],     label='Train')
    ax1.plot(history.history['val_accuracy'], label='Val')
    ax1.set_title('Accuracy'); ax1.legend()
    ax2.plot(history.history['loss'],     label='Train')
    ax2.plot(history.history['val_loss'], label='Val')
    ax2.set_title('Loss'); ax2.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(model_dir, 'training_history.png'), dpi=150)
    plt.close()

    # ── Save final model ──
    model.save(os.path.join(model_dir, 'gait_cnn.h5'))
    print(f'\nModel saved -> {os.path.join(model_dir, "gait_cnn.h5")}')
    print(f'Best checkpoint -> {os.path.join(model_dir, "gait_cnn_best.h5")}')
    print(f'Confusion matrix -> {os.path.join(model_dir, "gait_confusion_matrix_cnn.png")}')
    print(f'Training history -> {os.path.join(model_dir, "training_history.png")}')


if __name__ == '__main__':
    main()
